default: true

extends: null

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013/line-length - Line length
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false
